In [8]:
import numpy as np

x = np.array([1,2,3])
W = np.array([[1,2],[3,4],[5,6]])
b = np.array([-1, 2])


print(x)
print(x.shape)


[1 2 3]
(3,)


In [9]:
print(W)
print(W.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
print(b)
print(b.shape)

[-1  2]
(2,)


In [15]:
dot = np.dot(x, W)

In [16]:
print(dot)

[22 28]


In [17]:
print(dot + b)

[21 30]


In [20]:
def setW(sizein, sizeout):
    W = np.random.uniform(low = -0.0001, high = 0.0001, size = (sizein, sizeout))
    return W

In [22]:
print(setW(3,2))

[[-4.88113343e-05  9.19535533e-05]
 [-1.68113383e-05  8.18411765e-05]
 [ 6.60204799e-05  3.12450273e-05]]


In [30]:
##forming a 1 x sizeout matrix
def setb(sizeout):
    b = np.random.uniform(low = -0.0001, high =  0.0001, size = (1, sizeout))
    return b

In [31]:
bias1 = setb(2)

In [32]:
print(bias1)

[[8.23623430e-05 1.86717642e-05]]


In [33]:
bias1.shape

(1, 2)